// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function ArchiveProject(arg1:number):Promise<void>;

export function ArchiveTask(arg1:number):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateProject(arg1:models.Project):Promise<void>;

export function CreateReportSection(arg1:models.ReportSection):Promise<void>;

export function CreateStatusDefinition(arg1:models.StatusDefinition):Promise<void>;

export function CreateSubtask(arg1:models.Subtask):Promise<void>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function ExportToFile(arg1:string,arg2:string):Promise<void>;

export function FinalizeReport(arg1:number,arg2:string):Promise<models.ReportSnapshot>;

export function GenerateReport(arg1:number,arg2:string):Promise<services.GeneratedReport>;

export function GetExportService():Promise<services.ExportService>;

export function GetProject(arg1:number):Promise<models.Project>;

export function GetProjectService():Promise<services.ProjectService>;

export function GetProjectStylesheet(arg1:number):Promise<string>;

export function GetReportSection(arg1:number):Promise<models.ReportSection>;

export function GetReportService():Promise<services.ReportService>;

export function GetReportSnapshot(arg1:number):Promise<models.ReportSnapshot>;

export function GetSubtask(arg1:number):Promise<models.Subtask>;

export function GetSuggestedFilepath(arg1:number,arg2:string):Promise<string>;

export function GetTask(arg1:number):Promise<models.Task>;

export function GetTaskService():Promise<services.TaskService>;

export function ListActiveProjects():Promise<Array<models.Project>>;

export function ListArchivedProjects():Promise<Array<models.Project>>;

export function ListReportSections(arg1:number):Promise<Array<models.ReportSection>>;

export function ListReportSnapshots(arg1:number):Promise<Array<models.ReportSnapshot>>;

export function ListStatusDefinitions(arg1:number):Promise<Array<models.StatusDefinition>>;

export function ListSubtasksByTask(arg1:number):Promise<Array<models.Subtask>>;

export function ListTasksBySection(arg1:number):Promise<Array<models.Task>>;

export function MoveTaskToSection(arg1:number,arg2:number):Promise<void>;

export function ReorderSections(arg1:number,arg2:Array<number>):Promise<void>;

export function ReorderTasks(arg1:number,arg2:Array<number>):Promise<void>;

export function RestoreSubtask(arg1:number):Promise<void>;

export function RestoreTask(arg1:number):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SoftDeleteAllSubtasks(arg1:number):Promise<void>;

export function SoftDeleteSubtask(arg1:number):Promise<void>;

export function SoftDeleteTask(arg1:number):Promise<void>;

export function UpdateProject(arg1:models.Project):Promise<void>;

export function UpdateProjectStylesheet(arg1:number,arg2:string):Promise<void>;

export function UpdateReportSection(arg1:models.ReportSection):Promise<void>;

export function UpdateStatusDefinition(arg1:models.StatusDefinition):Promise<void>;

export function UpdateSubtask(arg1:models.Subtask):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;
