// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function ArchiveTask(arg1) {
  return window['go']['main']['App']['ArchiveTask'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateReportSection(arg1) {
  return window['go']['main']['App']['CreateReportSection'](arg1);
}

export function CreateStatusDefinition(arg1) {
  return window['go']['main']['App']['CreateStatusDefinition'](arg1);
}

export function CreateSubtask(arg1) {
  return window['go']['main']['App']['CreateSubtask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function ExportToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportToFile'](arg1, arg2);
}

export function FinalizeReport(arg1, arg2) {
  return window['go']['main']['App']['FinalizeReport'](arg1, arg2);
}

export function GenerateReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2);
}

export function GetExportService() {
  return window['go']['main']['App']['GetExportService']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectService() {
  return window['go']['main']['App']['GetProjectService']();
}

export function GetProjectStylesheet(arg1) {
  return window['go']['main']['App']['GetProjectStylesheet'](arg1);
}

export function GetReportSection(arg1) {
  return window['go']['main']['App']['GetReportSection'](arg1);
}

export function GetReportService() {
  return window['go']['main']['App']['GetReportService']();
}

export function GetReportSnapshot(arg1) {
  return window['go']['main']['App']['GetReportSnapshot'](arg1);
}

export function GetSubtask(arg1) {
  return window['go']['main']['App']['GetSubtask'](arg1);
}

export function GetSuggestedFilepath(arg1, arg2) {
  return window['go']['main']['App']['GetSuggestedFilepath'](arg1, arg2);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskService() {
  return window['go']['main']['App']['GetTaskService']();
}

export function ListActiveProjects() {
  return window['go']['main']['App']['ListActiveProjects']();
}

export function ListArchivedProjects() {
  return window['go']['main']['App']['ListArchivedProjects']();
}

export function ListReportSections(arg1) {
  return window['go']['main']['App']['ListReportSections'](arg1);
}

export function ListReportSnapshots(arg1) {
  return window['go']['main']['App']['ListReportSnapshots'](arg1);
}

export function ListStatusDefinitions(arg1) {
  return window['go']['main']['App']['ListStatusDefinitions'](arg1);
}

export function ListSubtasksByTask(arg1) {
  return window['go']['main']['App']['ListSubtasksByTask'](arg1);
}

export function ListTasksBySection(arg1) {
  return window['go']['main']['App']['ListTasksBySection'](arg1);
}

export function MoveTaskToSection(arg1, arg2) {
  return window['go']['main']['App']['MoveTaskToSection'](arg1, arg2);
}

export function ReorderSections(arg1, arg2) {
  return window['go']['main']['App']['ReorderSections'](arg1, arg2);
}

export function ReorderTasks(arg1, arg2) {
  return window['go']['main']['App']['ReorderTasks'](arg1, arg2);
}

export function RestoreSubtask(arg1) {
  return window['go']['main']['App']['RestoreSubtask'](arg1);
}

export function RestoreTask(arg1) {
  return window['go']['main']['App']['RestoreTask'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SoftDeleteAllSubtasks(arg1) {
  return window['go']['main']['App']['SoftDeleteAllSubtasks'](arg1);
}

export function SoftDeleteSubtask(arg1) {
  return window['go']['main']['App']['SoftDeleteSubtask'](arg1);
}

export function SoftDeleteTask(arg1) {
  return window['go']['main']['App']['SoftDeleteTask'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectStylesheet(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectStylesheet'](arg1, arg2);
}

export function UpdateReportSection(arg1) {
  return window['go']['main']['App']['UpdateReportSection'](arg1);
}

export function UpdateStatusDefinition(arg1) {
  return window['go']['main']['App']['UpdateStatusDefinition'](arg1);
}

export function UpdateSubtask(arg1) {
  return window['go']['main']['App']['UpdateSubtask'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
